language: swift
osx_image: xcode10.1
before_install:
- set -o pipefail
- xcrun simctl boot "iPhone XR" || echo "(Pre)Launched the simulator."
script:
- cd Framework
- bundle install
- bundle exec fastlane build
- cd ..
- pod lib lint
- pod spec lint