name: CI

on: [push]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        action:
          - iOS
    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app
    - name: Install and Test
      run: cd Framework; bundle install; bundle exec fastlane build
